# Development Profile
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.filestore=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.devtools.restart.enabled=true